export enum UserRoleEnum {
    DELETE_ACCOUNT = 'DELETE_ACCOUNT',
    CHANGE_EMAIL_ACCOUNT = 'CHANGE_EMAIL_ACCOUNT',
    VALID_EMAIL_ACCOUNT = 'VALID_EMAIL_ACCOUNT',
    CHANGE_USER_ACCOUNT_TO_ADMIN = 'VALID_EMAIL_ACCOUNT',
    CHANGE_PASSWORD_ACCOUNT = 'CHANGE_PASSWORD_ACCOUNT',
}